name: Rust WebAssembly 包

on:
  push:
    branches:
      - cargo-package

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: 安装 wasm-pack
        run: cargo install wasm-pack

      - name: 登陆 crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: 打包 Rust 包
        run: cargo package
        # 添加错误处理，确保只在成功打包时尝试发布
        continue-on-error: false

      - name: 检查包版本是否已存在
        id: check-version
        run: |
          # 获取当前包名和版本
          PACKAGE_NAME=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].name')
          PACKAGE_VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].version')

          # 检查该版本是否已在crates.io上发布
          if cargo search $PACKAGE_NAME | grep -q $PACKAGE_VERSION; then
            echo "版本 $PACKAGE_VERSION 已存在，跳过发布"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "版本 $PACKAGE_VERSION 尚未发布，将继续发布"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: 发布到 crates.io
        if: steps.check-version.outputs.should_publish == 'true'
        run: cargo publish
