name: Rust WebAssembly 包

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: 安装 wasm-pack
        run: cargo install wasm-pack

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: 执行 build_and_merge.sh 脚本
        run: ./build_and_merge.sh

      - name: 检查包版本是否已存在
        id: check-version
        working-directory: pkg
        run: |
          # 获取当前包名和版本
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          # 检查该版本是否已在npm上发布
          if npm view $PACKAGE_NAME@$PACKAGE_VERSION version >/dev/null 2>&1; then
            echo "版本 $PACKAGE_VERSION 已存在，跳过发布"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "版本 $PACKAGE_VERSION 尚未发布，将继续发布"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: 发布到 Node Packages
        if: steps.check-version.outputs.should_publish == 'true'
        working-directory: pkg
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
